info:
  version: 1.0.0
  description: NWDAF initial local configuration

configuration:
  containerName: nwdaf-mtlf
  sqlLiteDB: ml_model_info.db # a valid PATH of the SqlLite
  name: nwdaf-mtlf
  nwdafName: NWDAF-MTLF # the name of this NWDAF

  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.1 # IP used to register to NRF
    bindingIPv4: 127.0.0.1 # IP used to bind the service
    port: 4202 # port used to bind the service

  nrfUri: http://127.0.0.1:4200 # a valid URI of NRF
  oamUri: http://127.0.0.1:30090 # a valid URI of PCM (Packet Capture Module)
  ksmInstance: "kube-state-metrics.kube-system.svc.cluster.local:8080" # a valid kube-state-metrics instance
  namespace: "free5gc" # namespace of 5GC

  mlModelTrainingInfo:
    timeSteps: 4 # a valida int to time series

  serviceNameList: # the SBI services provided by this MTLF, refer to TS 29.518
    - nnwdaf-mlmodelprovision # Nnwdaf_MLModelProvision service
    - nnwdaf-mlmodelinfo # Nnwdaf_MLModelInfo service
    - nnwdaf-mlmodeltraining # Nnwdaf_MLModelTraining service

  networkName: # the name of this core network
    full: free5GC
    short: free


logger:
  NWDAF:
    debugLevel: info
    ReportCaller: false
