package util

var (
	NwdafDefaultKeyLogPath               = "./log/nwdafsslkey.log"
	NwdafDefaultPemPath                  = "./config/TLS/nwdaf.pem"
	NwdafDefaultKeyPath                  = "./config/TLS/nwdaf.key"
	NwdafDefaultConfigPath               = "./config/nwdafcfg-mtlf.yaml"
	NwdafDefaultDataPath                 = "./data/"
	NwdafDefaultDataRawPath              = "./data/raw/"
	NwdafDefaultDataPreprocessedPath     = "./data/preprocessed/"
	NwdafDefaultDataProcessedPath        = "./data/processed/"
	NwdafDefaultDataLabeledPath          = "./data/labeled/"
	NwdafDefaultDataProcessingScriptPath = "./ml_model_training_scripts/data_processing.py"
	NwdafDefaultModelTrainingScriptPath  = "./ml_model_training_scripts/ml_model_training.py"
	NwdafDefaultModelsPath               = "./models/"
	NwdafDefaultFiguresPath              = "./models/figures/"
	NwdafDefaultModelInfoFile            = "model_info.json"
	NwdafDefaultModelInfoListFile        = "model_info_list.json"
	NwdafDefaultInitModelInfoListFile    = "default_models_list.json"
	NwdafDefaultMenUsageFile             = "memUsage.json"
	NwdafDefaultCpuUsageFile             = "cpuUsage.json"
	NwdafDefaultTotalThroughputFile      = "totalThroughput.json"
	NwdafDefaultDatasetBase64Prefix      = "data:text/csv;base64,"
	NwdafDefaultDatasetNameFormat        = "dataset_NF_LOAD_AMF_60s_1733802540_1733828626.csv"
)
